### ISSUE TITLE
Chef issue with vulnerability-detector adds only one feed

### ISSUE THREAD

**Issue by sc7565** [wazuh/wazuh-chef#10]
With below configuration, the expected number of feeds are two, but actually it adds only the latest one i.e ubuntu-16

default['ossec']['conf']['server']['wodle'] = [
    { '@name' => 'vulnerability-detector', 'content!' => {
        'disabled' => 'no',
        'interval' => '1m',
        'run_on_start' => 'yes',
        'feed' => { '@name' => 'ubuntu-14' , 'content!' =>
            {
                'disabled' => 'no',
                'update_interval' => '1h',
            }
        },
        'feed' => { '@name' => 'ubuntu-16' , 'content!' =>
            {
                'disabled' => 'no',
                'update_interval' => '1h',
            }
        },
      }
    },
]

**Comment by manuasir** [comment]
Hello @sc7565 ,

Sorry for the late response. We will check this out and will let you know about any solution.
Thanks for reporting it.

Regards

**Comment by curiositycasualty** [comment]
Oh hey, actually this is already possible:
```ruby
default['ossec']['conf']['server']['wodle'] = [
  {
    '@name' => 'vulnerability-detector',
    'content!' => {
      'disabled' => 'no',
      'interval' => '5m',
      'run_on_start' => 'yes',
      'feed' => [
        {
          '@name' => "ubuntu-18" ,
          'content!' => {
            'disabled' => 'no',
            'update_interval' => '1h',
          }
        },
        {
          '@name' => "ubuntu-16" ,
          'content!' => {
            'disabled' => 'no',
            'update_interval' => '1h',
          }
        }
      ]
    }
  }
]
```

Generates:
```xml
    <feed name="ubuntu-18">
      <disabled>no</disabled>
      <update_interval>1h</update_interval>
    </feed>
    <feed name="ubuntu-16">
      <disabled>no</disabled>
      <update_interval>1h</update_interval>
    </feed>
```

`feed` just needs to be an array of hashes.

/cc @jm404

**Comment by jm404** [comment]
I've found this behavior previously when implementing new features.

When rendering, if Gyoku finds a label with same name, will override the previous one. So in your example @sc7565: 

```xml
default['ossec']['conf']['server']['wodle'] = [    
    { '@name' => 'vulnerability-detector', 'content!' => {
            'disabled' => 'no',
            'interval' => '1m',
            'run_on_start' => 'yes',
            'feed' => { '@name' => 'ubuntu-14' , 'content!' =>
                {
                'disabled' => 'no',
                'update_interval' => '1h',
                }
            },
            'feed' => { '@name' => 'ubuntu-16' , 'content!' =>
                {
                'disabled' => 'no',
                'update_interval' => '1h',
                }
            },
            }
    },
]
```

Will result in:
```xml
    <feed name="ubuntu-16">
      <disabled>no</disabled>
      <update_interval>1h</update_interval>
    </feed>
```


The `feed`  block will be **overridden**, as it's declared multiple times **the last one will prevail.**

As @curiositycasualty stated you have to declare it as an array of hashes, declaring with `@` the attributes and with `content!` the content of such block.

I recently implemented the wodle code in the default attributes of wazuh-manager. You can find it [here](https://github.com/wazuh/wazuh-chef/blob/3.9/cookbooks/wazuh_manager/attributes/wodle.rb).

Also, let me mention the  [Gyoku repository](https://github.com/savonrb/gyoku) where you can find some useful examples.

Best Regards!

Jose

**Comment by jm404** [comment]
Hi @sc7565 ,

Did you managed to solve it with the proposed code as array of hashes?

Best Regards,

Jose

**Comment by manuasir** [comment]
Hi @sc7565,

This issue is going to be closed due to inactivity. Don't hesitate to open a new ticket if you need it, we'll be glad to help you.

Cheers
