### ISSUE TITLE
404 error when downloading the Oracle Java JDK

### ISSUE THREAD

**Issue by LuisGi93** [wazuh/wazuh-chef#12]
Right now the chef recipes will fail when is needed to download the Oracle JDK:

![screenshot_8](https://user-images.githubusercontent.com/17405573/56740110-91b3f980-6770-11e9-804a-c8af87cd401e.png)

Like could be seen at the above screenshot the file that is used to install Oracle JDK is missing from the provided url.

**Comment by jm404** [comment]
Hi team!
Overwritting *java.rb* recipe with the following code fixes the problem ( ONLY tested on Ubuntu 16.04).

```case node['platform']
when 'ubuntu'
  package 'lsb-release'

  ohai 'reload lsb' do
    plugin 'lsb'
    # action :nothing
    subscribes :reload, 'package[lsb-release]', :immediately
  end

  apt_repository 'java' do
    uri 'ppa:openjdk-r/java'
    distribution node['lsb']['codename']
    not_if {node['platform_version'].to_f > 16.0}
  end

  apt_update 'update'
  package 'openjdk-8-jre'

when 'redhat', 'centos'

  yum_package 'java-1.8.0-openjdk' do
    
  end

end
