### ISSUE TITLE
Wazuh Cluster implementation is customizable and hasn't been tested.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#27]
Hi team,

Despite the fact that Filebeat is installed by default, the installation of Wazuh with the Cluster configuration has not been tested.
 
Also, some parameters would make the installation much more customizable like the ```hosts``` field in *filebeat.yml*.

### Tasks

- [x] Implement required parameters to customize the Wazuh Cluster 

- [x] Test configuration

- [x] Update READMEs to document changes and new attributes.

Regards!

Jose

**Comment by manuasir** [comment]
Done #30
