### ISSUE TITLE
Update Chef to Elastic 7.1.0

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#28]
Wazuh version: 3.9.1
Elastic version: 7.1.0

- [x] Adapt to new versions (3.9.1 - 7.1.0)
- [x] Update changelog
- [x] Tests
- [x] Tag: v3.9.1
- [x] Draft release

**Comment by curiositycasualty** [comment]
Could probably save some headache by making `wazuh_elastic::repository` split `node['wazuh-elastic']['elastic_stack_version']` and use the major version number in the `apt_repository` resource.

Something like:
```ruby
  es_version = node['wazuh-elastic']['elastic_stack_version']
  es_major, es_minor, es_patch = es_version.split('.')
  apt_repository "elastic-#{es_major}.x" do
    uri 'https://artifacts.elastic.co/packages/#{es_major}.x/apt'
    key 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
    distribution "stable"
    components ["main"]
    not_if do
      File.exists?("/etc/apt/sources.list.d/elastic-#{es_major}.x.list")
    end
  end
```

**Comment by jm404** [comment]
Hi @curiositycasualty ,

As we are facing new versions, some management of major is totally needed and your example gives a good reference to achieve that objetive.

We are working on the update and will implement such version management and test them as soon as possible.

Thank you very much for your contributions!

Best Regards

**Comment by manuasir** [comment]
Done #30
