### ISSUE TITLE
Upload to supermarket?

### ISSUE THREAD

**Issue by atheiman** [wazuh/wazuh-chef#3]
Im going to upload this to the supermarket. if anyone ever wants to take over ownership on the supermarket, email me.

**Comment by atheiman** [comment]
ive uploaded it here https://supermarket.chef.io/cookbooks/wazuh

**Comment by jlruizmlg** [comment]
Hi @atheiman thanks a lot for your upload to the supermarket and sorry for the late response! if you don't mind we want to take the ownership, it will be easier for us apply the last changes in the code.

**Comment by atheiman** [comment]
of course, I just needed it done quickly so I did it myself. I'll try to add you now on supermarket.chef.io as an owner.

**Comment by jlruizmlg** [comment]
Let me know if I can help with that :)

**Comment by atheiman** [comment]
I just transferred ownership to you, you should get an email @jlruizmlg

**Comment by jlruizmlg** [comment]
Got it! I have it! thanks a lot!!
