### ISSUE TITLE
Rootkit files path of Agent is misconfigured

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#44]
Hi team,

In the Wazuh Agent, the path of `rootkit_files` and `rootkit_trojans` is misconfigured.

https://github.com/wazuh/wazuh-chef/blob/fe773bc632a51431a6dbfd8a3de942b4c585d425/cookbooks/wazuh_agent/attributes/rootcheck.rb#L11-L12

It should be `#{node['ossec']['dir']}/etc/shared/rootkit_files.txt` and `#{node['ossec']['dir']}/etc/shared/rootkit_trojans.txt` respectively.

##### Tasks

- [x] Reconfigure default agent attributes

- [x] Run installation and check logs for errors

Best regards

Jose

**Comment by rshad** [comment]
Hi all,

Changes were applied as you can see here:

https://github.com/wazuh/wazuh-chef/blob/68bb88ee62d771fcac2d0bf63ea070c25f168aac/cookbooks/wazuh_agent/attributes/rootcheck.rb#L11-L12.

We also assigned a default value for `elasticsearch_ip` and `filebeat_ip` as you can check here:

https://github.com/wazuh/wazuh-chef/blob/68bb88ee62d771fcac2d0bf63ea070c25f168aac/cookbooks/wazuh_elastic/attributes/elasticsearch.rb#L20

https://github.com/wazuh/wazuh-chef/blob/68bb88ee62d771fcac2d0bf63ea070c25f168aac/cookbooks/wazuh_filebeat/attributes/default.rb#L10

Changes were tested by running a real installation of Wazuh using `wazuh-chef` with the applied changes. All components were started with no errors in the logs.

Kind regards,

Rshad

**Comment by manuasir** [comment]
Done here #48

**Comment by rshad** [comment]
Hi all!

Edit: **Reverted** the change "We also assigned a default value for `elasticsearch_ip` and `filebeat_ip` ..."

****After Reverting:****

https://github.com/wazuh/wazuh-chef/blob/37f427d86bbbc14bd11d438dc05b24ba827f6327/cookbooks/wazuh_elastic/attributes/elasticsearch.rb#L20

https://github.com/wazuh/wazuh-chef/blob/37f427d86bbbc14bd11d438dc05b24ba827f6327/cookbooks/wazuh_filebeat/attributes/default.rb#L10

Kr,

Rshad
