### ISSUE TITLE
chef chco 

### ISSUE THREAD

**Issue by necrose99** [wazuh/wazuh-chef#7]
chocolatey_package 'ossec.wazuh.agent' do
  notifies                   # see description
  options                    String
  package_name               String, Array # defaults to 'name' if not specified
  source                     String
  subscribes                 # see description
  timeout                    String, Integer
  version                    String, Array
  returns                    Integer, Array of Integers
  action                     Symbol # defaults to :install if not specified
end

need to update choco repo , as well one could add to cookbook to replace stings in config file. 
ie ip address.. anyrate  , could batch build deploys.. 
https://github.com/m-dwyer/packer-malware 
https://github.com/GoSecure/malboxes  
could also add to malboxes to get the sig into the SIEM ... 

aswell , also salt , puppet ansible , etc cookbooks can likewise use choco as backend.. 

https://chocolatey.org/packages/ossec.wazuh.agent/3.5.0.1

**Comment by necrose99** [comment]
[ossec.wazuh.agent.3.5.0.1.nupkg.zip](https://github.com/wazuh/wazuh-chef/files/2281589/ossec.wazuh.agent.3.5.0.1.nupkg.zip)
https://docs.chef.io/resource_chocolatey_package.html

**Comment by manuasir** [comment]
Hello @necrose99 ,

Apologies for the late response. You're right, it should be necessary to update the Chocolatey packages. I'll let you know when we take a look into it and they're updated to the latest version. 
Thank you for your concern.

Regards
