### ISSUE TITLE
Give option of using chef-vault instead of encrypted databag

### ISSUE THREAD

**Issue by shauryagarg2006** [wazuh/wazuh-chef#8]
In wazhu-api recipe it assumes e=ncrypted databags being used for storing api keys. It will be a neat to give user choice to use chef vault as well.

**Comment by manuasir** [comment]
Hello @shauryagarg2006 ,

Sorry for the late response. This is a very interesting feature, we will study the implementation and its implications with the current code and will let you know about it. Please, stay tuned here.

Regards

**Comment by jm404** [comment]
Hi @shauryagarg2006,

Sorry for the late response,

We evaluated Chef Vault and after considering the advantages of it we will implement it in our repository to manage secrets and cipher sensible information. According to this, we are including it in our roadmap.

Thank you for your contribution and feedback, we really appreciate it!

Best regards,

Jose

**Comment by manuasir** [comment]
Done here #47 , this issue is going to be closed.
@shauryagarg2006 I'd like to thank you for collaborating with this project. Much appreciated.
Please don't hesitate to open a new ticket whenever you may need it.

Cheers

**Comment by shauryagarg2006** [comment]
Thanks @manuasir  @jm404 
Sorry for the late response from my side as well :)
